name: cdk
 
on:
  push:
    branches:
      - masterr
jobs:
  aws_cdk:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
 
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
 
      - name: Setup dependencies
        run: yarn
 
      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
 